kind: pipeline
name: default

steps:
- name: build
  image: chodak166/dev-cpp:focal-base-1.0
  commands:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake
    -D CMAKE_BUILD_TYPE=Release
    -D CPPPS_DL_USE_BOOST=OFF
    -D CPPPS_DL_UNIT_TESTS_BUILD=ON
    -D CPPPS_DL_INTEGRATION_TESTS_BUILD=ON
    ..
  - cmake --build .

  - cd ..
  - mkdir build-boost
  - cd build-boost
  - cmake
    -D CMAKE_BUILD_TYPE=Release
    -D CPPPS_DL_USE_BOOST=ON
    -D CPPPS_DL_INTEGRATION_TESTS_BUILD=ON
    -D CPPPS_LOGGING_BUILD=OFF
    ..
  - cmake --build .

- name: test
  image: chodak166/dev-cpp:focal-base-1.0
  commands:
  - cd build
  - ctest -V .

  - cd ../build-boost
  - ctest -V .
