# Build:
# docker build -t cppps-jammy -f Dockerfile-jammy .
#
# Run:
# docker run --rm -v $PWD/..:/usr/src/cppps -e OWNER=${UID} cppps-jammy

FROM chodak166/dh-cmake:jammy

WORKDIR /usr/src

VOLUME ["/usr/src/cppps"]

ENV OWNER=1000
ENV OUT_DIR=deb-jammy

COPY entrypoint.sh /

ENTRYPOINT [ "/entrypoint.sh" ]
