# Build:
# docker build -t cppps-focal -f Dockerfile-focal .
#
# Run:
# docker run --rm -v $PWD/..:/usr/src/cppps -e OWNER=${UID} cppps-focal

FROM chodak166/dh-cmake:focal

WORKDIR /usr/src

VOLUME ["/usr/src/cppps"]

ENV OWNER=1000
ENV OUT_DIR=deb-focal

COPY entrypoint.sh /

ENTRYPOINT [ "/entrypoint.sh" ]
